title: Meritxell Colet
url: "MeritxellC.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./img/favicon.png"

remote_theme: ankitsultana/researcher@gem

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "https://meritxellc.github.io"
 - name: "Publications"
   link: "https://meritxellc.github.io/publications/publications"
 - name: "CV"
   link: "https://meritxellc.github.io/cv/cv"
 - name: "Contact"
   link: "https://meritxellc.github.io/contact"
