title: Meritxell Colet
url: ""
baseurl: "https://www.meritxellcolet.com/"

markdown: kramdown
#ins_logo: "./img/favicon.png"

remote_theme: ankitsultana/researcher@gem

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "https://www.meritxellcolet.com"
 - name: "Publications"
   link: "https://www.meritxellcolet.com/publications/publications"
 - name: "CV"
   link: "https://www.meritxellcolet.com/cv/cv"

